name: MyManualBuild
on:
  #push:
  #  branches:
  #  - main
  workflow_dispatch:
env:
  user_name: "Tom"
  demo_name: "Variables"
jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    env:
      job_var1: "job variable value"
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        env:
          step_var1: "step variable value"
        run: echo Hello, world! $user_name $demo_name $job_var1 $step_var1
      - name: Run a multi-line script
        run: |
          echo Add other actions to build
          echo test, and deploy your project.
          echo CI: $CI
          echo HOME: $HOME
          echo GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
          echo GITHUB_WORKSPACE: $GITHUB_WORKSPACE
          echo secret: ${{ secrets.MY_SECRET1 }}
          echo GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
